---
- name: Setup grafana files
  when: grafana_enabled is true
  block:
    - name: Copy provisioning directory
      ansible.builtin.copy:
        src: "{{ role_path }}/files/provisioning"
        dest: '{{ grafana_data_directory }}'
        force: true
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"
      notify: Restart grafana

    - name: Copy all dashboards
      ansible.builtin.copy:
        src: "{{ role_path }}/files/dashboards"
        dest: '{{ grafana_data_directory }}'
        force: true
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

- name: Start stack
  when: grafana_enabled is true
  block:
    - name: Make sure nas default network exists
      community.docker.docker_network:
        name: nas
        state: present

    - name: Make sure compose directory exists
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/grafana'
        state: directory
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Copy compose
      ansible.builtin.template:
        src: '{{ role_path }}/templates/docker-compose.yml'
        dest: '{{ nas_docker_compose_dir }}/grafana/docker-compose.yml'
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Start stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/grafana'
        state: present
        pull: missing
        remove_orphans: true

- name: Stop stack
  when: grafana_enabled is false
  block:
    - name: Tear down existing stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/grafana'
        state: absent

    - name: Remove compose files
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/grafana'
        state: absent
