---
- name: Nas setup
  hosts: all

  # vars:
  #   ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Disable cron mailing to root
      community.general.cronvar:
        name: MAILTO
        value: "\"\""
        # value: "danielbibit@gmail.com"
        user: root

  roles:
    - role: install_packages
      tags:
        - system

    # - role: create_users
    #   tags:
    #     - system

    - role: setup_cron
      tags:
        - system

    - role: samba
      tags:
        - samba
        - system

    - role: configure_email
      tags:
        - email
        - system
        - monitoring

    - role: monitoring
      tags:
        - monitoring
        - system

    - role: reports
      tags:
        - reports
        - system

    - role: automated_backups
      tags:
        - backups
        - system

    - role: glances
      tags:
        - glances
        - monitoring
        - docker

    - role: grafana
      tags:
        - grafana
        - monitoring
        - docker

    - role: node_exporter
      tags:
        - node_exporter
        - monitoring
        - docker

    - role: prometheus
      tags:
        - prometheus
        - monitoring
        - docker

    - role: cadvisor
      tags:
        - cadvisor
        - monitoring
        - docker

    - role: promtail
      tags:
        - promtail
        - monitoring
        - docker

    - role: loki
      tags:
        - loki
        - monitoring
        - docker

    - role: immich
      tags:
        - immich
        - docker

    - role: nginx_proxy_manager
      tags:
        - nginx_proxy_manager
        - networking
        - docker

    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
        - networking
        - docker
