# Todo make systemd service
- name: Daily docker sync
  ansible.builtin.cron:
    name: "daily_sync_docker_mounts"
    hour: "04"
    minute: "00"
    user: root
    state: absent
    job: "rsync -a {{ nas_docker_directory }}/ {{ nas_backup_dir }}/NAS/docker"
