---
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    container_name: cadvisor
    ports:
      - "{{ cadvisor_port }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-housekeeping_interval=10s'
    restart: "always"

networks:
  default:
    name: nas
    external: true
