---
- name: Start Immich stack
  when: immich_enabled is true
  block:
    - name: Make sure nas default network exists
      community.docker.docker_network:
        name: nas
        state: present

    - name: Make sure compose directory exists
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/immich'
        state: directory
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Copy Immich compose
      ansible.builtin.template:
        src: '{{ role_path }}/templates/docker-compose.yml'
        dest: '{{ nas_docker_compose_dir }}/immich/docker-compose.yml'
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Tear down existing Immich stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/immich'
        state: absent

    - name: Start Immich stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/immich'
        state: present
        pull: missing
        remove_orphans: true

- name: Stop Immich stack
  when: immich_enabled is false
  block:
    - name: Tear down existing Immich stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/immich'
        state: absent

    - name: Remove Immich compose files
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/immich'
        state: absent
