{
 "title": "Node Stats - nas",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$host\"} - node_memory_MemAvailable_bytes{instance=~\"$host\"}) / node_memory_MemTotal_bytes{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host\"}"
    },
    {
     "expr": "node_load5{instance=~\"$host\"}"
    },
    {
     "expr": "node_load15{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Free Disk root",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\", instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$host\", sensor=~\"temp1\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$host\", sensor=~\"temp1\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n                100 * sum(\n                    rate(node_cpu_seconds_total{ mode=~\"system|user\", instance=~\"$host\" }[$__rate_interval])\n                )\n                /\n                count(\n                    node_cpu_seconds_total{ mode=\"user\", instance=~\"$host\" }\n                )\n                "
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_written_bytes_total{instance=~\"$host\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$host\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "File Systems",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n                100 - (\n                    node_filesystem_avail_bytes{\n                        device != \"tmpfs\",\n                        instance=~\"$host\"\n                    } * 100\n                ) /\n                node_filesystem_size_bytes{\n                    device != \"tmpfs\",\n                    instance=~\"$host\"\n                }\n                "
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "-rate(node_network_receive_bytes_total{instance=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}