---
# Create Groups
- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ system_groups }}"

# Create users
- name: Create Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    state: present
  with_items: "{{ system_users }}"
