---
services:
  node_exporter:
    container_name: "node_exporter"
    image: "quay.io/prometheus/node-exporter:latest"
    command:
      - "--path.rootfs=/host"
    restart: "unless-stopped"
    volumes:
      - "/:/host:ro"

networks:
  default:
    name: nas
    external: true
