---
- name: Start glances
  when: glances_enabled is true
  block:
    - name: Ensure glances container is running
      community.docker.docker_container:
        name: glances
        image: nicolargo/glances
        pid_mode: host
        network_mode: host
        env:
          GLANCES_OPT: "-w"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        security_opts:
          - "apparmor=unconfined"
        ports:
          - '{{ glances_external_port_1 }}:61208'
          - '{{ glances_external_port_2 }}:61209'
        restart_policy: unless-stopped


- name: Remove glances
  when: glances_enabled is false
  block:
    - name: Ensure glances container is stopped
      community.docker.docker_container:
        name: glances
        state: absent
