---
- name: Copy upgrade script
  ansible.builtin.copy:
    src: "{{ role_path }}/files/docker_upgrade.sh"
    dest: /home/{{ nas_admin }}/scripts
    owner: root
    mode: "775"

- name: Creates cron for auto update every sunday
  ansible.builtin.cron:
    name: monthly_docker_upgrade
    weekday: "0"
    hour: "20"
    minute: "00"
    user: root
    job: 'bash /home/{{ nas_admin }}/scripts/docker_upgrade.sh > /home/{{ nas_admin }}/scripts/docker_upgrade_output 2>&1'
    # job: 'bash /home/{{ nas_admin }}/scripts/docker_upgrade.sh | /urs/sbin/sendmail -t {{ email_report_to }}'
