---
promtail_enabled: false

promtail_port: 9080
promtail_dir: "{{ nas_docker_directory }}/promtail"
promtail_config_dir: "/etc/promtail"
promtail_loki_target: "http://192.168.1.11:3100/loki/api/v1/push"

__promtail_arch_map:
  x86_64: 'amd64'
  armv6l: 'arm'
  armv7l: 'arm'
  aarch64: 'arm64'

__promtail_arch: "{{ __promtail_arch_map[ansible_facts['architecture']] | default(ansible_facts['architecture']) }}"

promtail_version: "latest"
promtail_download_url_deb: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail_{{ promtail_version }}_{{ __promtail_arch }}.deb"
