http:
  routers:
    jellyfin:
      rule: "Host(`jellyfin.{{ traefik_domain }}`)"
      entryPoints:
        - websecure
      service: jellyfin-svc
      tls:
        certResolver: cloudflare
{% if not jellyfin_public | default(false) %}
      middlewares:
        - internal-only@file
{% endif %}
  services:
    jellyfin-svc:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"
