http:
  routers:
    immich:
      rule: "Host(`immich.{{ traefik_domain }}`)"
      entryPoints:
        - websecure
      service: immich-svc
      tls:
        certResolver: cloudflare
{% if not immich_public | default(false) %}
      middlewares:
        - internal-only@file
{% endif %}
  services:
    immich-svc:
      loadBalancer:
        servers:
          - url: "http://immich:8080"
