---
- name: Setup prometheus files
  when: prometheus_enabled is true
  block:
    - name: Template the config file
      ansible.builtin.template:
        src: "{{ role_path }}/templates/prometheus.yml"
        dest: '{{ prometheus_data_dir }}/prometheus.yml'
        force: true
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"
      notify: Restart prometheus

- name: Start stack
  when: prometheus_enabled is true
  block:
    - name: Make sure nas default network exists
      community.docker.docker_network:
        name: nas
        state: present

    - name: Make sure compose directory exists
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/prometheus'
        state: directory
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Copy compose
      ansible.builtin.template:
        src: '{{ role_path }}/templates/docker-compose.yml'
        dest: '{{ nas_docker_compose_dir }}/prometheus/docker-compose.yml'
        owner: '{{ nas_docker_uid }}'
        group: '{{ nas_docker_gid }}'
        mode: "0775"

    - name: Start stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/prometheus'
        state: present
        pull: missing
        remove_orphans: true

- name: Stop stack
  when: prometheus_enabled is false
  block:
    - name: Tear down existing stack
      community.docker.docker_compose_v2:
        project_src: '{{ nas_docker_compose_dir }}/prometheus'
        state: absent

    - name: Remove compose files
      ansible.builtin.file:
        path: '{{ nas_docker_compose_dir }}/prometheus'
        state: absent
