---
services:
  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "{{ promtail_port }}:9080"
    volumes:
      - "{{ promtail_dir }}/promtail-config.yml:/etc/promtail/config.yml"
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log:/var/log
    restart: "always"

networks:
  default:
    name: nas
    external: true
