http:
  routers:
    qbittorrent:
      rule: "Host(`qbittorrent.{{ traefik_domain }}`)"
      entryPoints:
        - websecure
      service: qbittorrent-svc
      tls:
        certResolver: cloudflare
{% if not qbittorrent_public | default(false) %}
      middlewares:
        - internal-only@file
{% endif %}
    qbitmanage:
      rule: "Host(`qbitmanage.{{ traefik_domain }}`)"
      entryPoints:
        - websecure
      service: qbitmanage-svc
      tls:
        certResolver: cloudflare
      middlewares:
        - internal-only@file
  services:
    qbittorrent-svc:
      loadBalancer:
        servers:
          - url: "http://gluetun:{{ qbittorrent_webui_port }}"
    qbitmanage-svc:
      loadBalancer:
        servers:
          - url: "http://qbit_manage:8080"
