---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "{{ nas_docker_compose_dir }}/syncthing/config:/config"
      - "{{ syncthing_data_dir }}:/data"
    ports:
      - "{{ syncthing_port }}:8384"
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

networks:
  default:
    name: nas
    external: true
