version: "3.5"
# https://techoverflow.net/2021/01/12/how-to-fix-gitlab-ci-error-during-connect-post-http-docker2375-v1-40-auth-dial-tcp-lookup-docker-on-no-such-host/
# https://techoverflow.net/2021/01/12/how-to-install-gitlab-runner-using-docker-compose/
# https://medium.com/@tonywooster/docker-in-docker-in-gitlab-runners-220caeb708ca
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
services:
  dind:
    container_name: gitlab_runner_dind
    image: docker:20-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    command:
      - --storage-driver=overlay2

  runner:
    container_name: gitlab_runner
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - /srv/Users/docker/gitlab-runner/config:/etc/gitlab-runner:z

  register-runner:
    container_name: gitlab_runner_register
    restart: 'no'
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    depends_on:
      - dind
    environment:
      - CI_SERVER_URL=https://gitlab.com
      - REGISTRATION_TOKEN={{ gitlab_registration_token }}
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=nas_runner
      - --executor=docker
      - --docker-image=docker:20-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - /srv/Users/docker/gitlab-runner/config:/etc/gitlab-runner:z
