version: '3.5'

services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY={{ cloudflare_api_key }}
      - ZONE={{ cloudflare_zone }}
      - SUBDOMAIN={{ cloudflare_subdomain }}
      - PROXIED=false

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '4280:80'
      - '42443:443'
    volumes:
      - /srv/Users/docker/nginxproxy/data:/data
      - /srv/Users/docker/nginxproxy/letsencrypt:/etc/letsencrypt
