version: '2'

services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /srv/Users/docker/immich:/config
      - /srv/Storage/Library/Pictures/immich:/photos
      - /srv/Storage/Library/Pictures:/libraries
    ports:
      - 8089:8080
    restart: unless-stopped

  immich_redis:
    container_name: immich_redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  immich_postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /srv/Users/docker/immich_postgres:/var/lib/postgresql/data
    restart: unless-stopped
