---
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - "{{ prometheus_data_dir }}:/etc/prometheus"
    restart: unless-stopped

networks:
  default:
    name: nas
    external: true
